import os
import re
import glob

def parse_skill_file(filepath):
    # Regex to find name, description, category in yaml frontmatter
    name, description, category = "Unknown", "No description provided.", "Uncategorized"
    
    if not os.path.exists(filepath):
        return None
        
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            content = f.read()
            # Match yaml frontmatter accurately
            match = re.search(r'^---\r?\n(.*?)\r?\n---\r?\n', content, re.DOTALL)
            if match:
                frontmatter = match.group(1)
                name_m = re.search(r'^name:\s*"?([^"\n]*)"?', frontmatter, re.MULTILINE)
                if name_m: name = name_m.group(1).strip()
                
                desc_m = re.search(r'^description:\s*"?([^"\n]*)"?', frontmatter, re.MULTILINE)
                if desc_m: description = desc_m.group(1).strip()
                
                cat_m = re.search(r'^category:\s*"?([^"\n]*)"?', frontmatter, re.MULTILINE)
                if cat_m: category = cat_m.group(1).strip()
                else:
                    category = "General"
    except Exception as e:
        pass
        
    return {
        "name": name,
        "description": description,
        "category": category,
        "path": filepath
    }

def main():
    skills_dir = os.path.expanduser('~/.gemini/antigravity/skills')
    skill_dirs = glob.glob(os.path.join(skills_dir, '*'))
    
    skills = []
    for d in skill_dirs:
        if os.path.isdir(d):
            skill_file = os.path.join(d, 'SKILL.md')
            parsed = parse_skill_file(skill_file)
            if parsed and parsed['name'] != 'Unknown':
                # format path relative to ~/.gemini
                parsed['path'] = f"`~/.gemini/antigravity/skills/{os.path.basename(d)}/`"
                skills.append(parsed)
                
    # Group by category
    categories = {}
    for s in skills:
        cat = s['category'].capitalize()
        # Some cleanup for default empty categories or messy ones
        if not cat or cat.lower() == 'none' or cat == '""':
            cat = 'General'
        if cat not in categories:
            categories[cat] = []
        categories[cat].append(s)
        
    # Sort categories and skills
    sorted_cats = sorted(categories.keys())
    for cat in sorted_cats:
        categories[cat] = sorted(categories[cat], key=lambda x: x['name'].lower())

    # Generate English Markdown
    en_md = ["# 🌐 Complete Antigravity Skills Directory\n\n"]
    en_md.append("> *Note: This directory is auto-generated by parsing local `SKILL.md` files.*\n\n")
    en_md.append(f"**Total Skills Found:** {len(skills)}\n\n")
    en_md.append("---\n\n")
    
    for cat in sorted_cats:
        en_md.append(f"## 📚 Category: {cat}\n")
        en_md.append("| Skill Name | Description | Source Path |\n")
        en_md.append("| :--- | :--- | :--- |\n")
        for s in categories[cat]:
            en_md.append(f"| **`@{s['name']}`** | {s['description']} | {s['path']} |\n")
        en_md.append("\n---\n\n")
        
    en_md.append("## 🧭 Navigation\n\n")
    en_md.append("| [🏠 Home](../../README.md) | [📓 Planning](./planning.md) | [🎨 Frontend](./frontend.md) |\n")
    en_md.append("| :---: | :---: | :---: |\n")
    en_md.append("| [🐍 Backend](./backend.md) | [🛡️ Security](./security.md) | [🧞 Agents](./agents.md) |\n")
    en_md.append("| [🧪 QA](./qa_testing.md) | [📦 Bundles](./bundles.md) | [🌊 Workflows](./workflows.md) |\n")
    en_md.append("| 🌐 **All Skills** | [🇰🇷 한국어 버전](../ko/all_skills_directory.md) | |\n\n")

    # Generate Korean Markdown
    ko_md = ["# 🌐 앤티그래비티 전체 스킬 디렉토리\n\n"]
    ko_md.append("> *참고: 이 문서는 로컬의 `SKILL.md` 파일들을 파싱하여 자동 생성되었습니다. (스킬 원본 설명은 원본 형태를 변형하지 않기 위해 영어로 유지됩니다.)*\n\n")
    ko_md.append(f"**조회된 총 스킬 개수:** {len(skills)}개\n\n")
    ko_md.append("---\n\n")
    
    for cat in sorted_cats:
        cat_ko = cat
        if cat.lower() == 'general': cat_ko = '일반 (General)'
        ko_md.append(f"## 📚 카테고리: {cat_ko}\n")
        ko_md.append("| 스킬명 (Skill Name) | 설명 (Description) | 위치 (Source Path) |\n")
        ko_md.append("| :--- | :--- | :--- |\n")
        for s in categories[cat]:
            ko_md.append(f"| **`@{s['name']}`** | {s['description']} | {s['path']} |\n")
        ko_md.append("\n---\n\n")
        
    ko_md.append("## 🧭 탐색 (Navigation)\n\n")
    ko_md.append("| [🏠 홈으로](../../README_KO.md) | [📓 기획 가이드](./planning.md) | [🎨 프론트엔드](./frontend.md) |\n")
    ko_md.append("| :---: | :---: | :---: |\n")
    ko_md.append("| [🐍 백엔드](./backend.md) | [🛡️ 보안](./security.md) | [🧞 에이전트](./agents.md) |\n")
    ko_md.append("| [🧪 QA 테스트](./qa_testing.md) | [📦 스킬 번들](./bundles.md) | [🌊 워크플로우](./workflows.md) |\n")
    ko_md.append("| 🌐 **전체 스킬 목록** | [🌐 English Version](../en/all_skills_directory.md) | |\n\n")
    
    # Save files
    base_dir = '/Users/giljae/workspaces/antigravity-skills'
    os.makedirs(os.path.join(base_dir, 'docs/en'), exist_ok=True)
    os.makedirs(os.path.join(base_dir, 'docs/ko'), exist_ok=True)
    
    with open(os.path.join(base_dir, 'docs/en/all_skills_directory.md'), 'w', encoding='utf-8') as f:
        f.write("".join(en_md))
        
    with open(os.path.join(base_dir, 'docs/ko/all_skills_directory.md'), 'w', encoding='utf-8') as f:
        f.write("".join(ko_md))
        
    print(f"Successfully generated catalogs with {len(skills)} skills!")

if __name__ == '__main__':
    main()
